# Generated by Django 4.2.8 on 2023-12-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tbl',
            name='mobile',
        ),
    ]
