# Generated by Django 4.2.8 on 2023-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0002_remove_user_tbl_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_tbl',
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='gram_of_product',
            field=models.IntegerField(null=True),
        ),
    ]
