# Generated by Django 4.2.8 on 2023-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0003_delete_user_tbl_product_tbl_gram_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='product_description',
            field=models.TextField(null=True),
        ),
    ]
