# Generated by Django 4.2.8 on 2024-01-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0005_product_tbl_stock'),
        ('cart', '0002_cartitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'b_id',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Direct_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.buy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiceapp.product_tbl')),
            ],
            options={
                'db_table': 'Direct_buy',
            },
        ),
    ]
