# Generated by Django 4.2.8 on 2024-01-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_buy_direct_buy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buy',
            table='Buy',
        ),
    ]
